env: &env
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  travis_token: <%= ENV["TRAVIS_TOKEN"] %>
  travis_repos: <%= ENV["TRAVIS_REPOS"] %>
  travis_test_mode: <%= !!ENV["TRAVIS_TEST_MODE"] %>

development:
  <<: *env

test:
  <<: *env

production:
  <<: *env
  